name       : zsh-autosuggestions
version    : 0.6.4
release    : 4
source     :
    - https://github.com/zsh-users/zsh-autosuggestions/archive/v0.6.4.tar.gz : 0b6e251ced5fd7b5b78ea01f798ecc1b46169743a717567f0ec0a21198a372e8
license    : MIT
component  : system.utils
summary    : Fish-like autosuggestions for zsh
description: |
    Fish-like fast/unobtrusive autosuggestions for zsh. It suggests commands as you type, based on command history.
builddeps  :
    - zsh
build      : |
    %make
install    : |
    install -Dm00644 $workdir/zsh-autosuggestions.zsh $installdir/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    install -Dm00644 $workdir/zsh-autosuggestions.plugin.zsh $installdir/usr/share/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
    install -Dm00644 $workdir/README.md $installdir/usr/share/doc/zsh-autosuggestions/README.md
